127.0.0.1 - - [18/Oct/2024 16:56:59] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2024 16:56:59] "GET /assets/stylesheets/main.0253249f.min.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2024 16:56:59] "GET /assets/javascripts/bundle.83f73b43.min.js HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2024 16:56:59] "GET /assets/logo.png HTTP/1.1" 200 -
127.0.0.1 - - [18/Oct/2024 16:56:59] "GET /assets/plane.png HTTP/1.1" 304 -
127.0.0.1 - - [18/Oct/2024 16:56:59] "GET /assets/favicon.ico HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 47894)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/http/server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/usr/lib/python3.10/http/server.py", line 675, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.10/http/server.py", line 875, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.10/shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
